# Git abbrs
abbr --add gadd     'git add'
abbr --add ga       'git add'
abbr --add grm      'git rm'
abbr --add glog     'git log'
abbr --add glogg    'git log --graph'
abbr --add gsha     'git log --pretty="%h" -1'
abbr --add gSHA     'git log --pretty="%H" -1'
abbr --add gstatus  'git status'
abbr --add gs       'git status'
abbr --add gdiff    'git diff --color=always'
abbr --add gpush    'git push'
abbr --add gpom     'git push origin master'
abbr --add gpfo     'git push --force origin'
abbr --add gpso     'git push --set-upstream origin (git rev-parse --abbrev-ref HEAD)'
abbr --add gpull    'git pull --rebase'
abbr --add gclone   'git clone'
abbr --add gc       'git commit'
abbr --add gcom     'git commit -m'
abbr --add gca      'git commit -am'
abbr --add gbl      'git blame'
abbr --add gck      'git checkout'
abbr --add gcb      'git checkout -b'
abbr --add gmnf     'git merge --no-ff'
abbr --add gmg      'git merge'
abbr --add gb       'git branch'
abbr --add gbr      'git branch'
abbr --add gbset    'git branch --set-upstream-to=origin/(git rev-parse --abbrev-ref HEAD)'
abbr --add grrr     'git rerere'
abbr --add gstash   'git stash'
abbr --add gst      'git stash'
abbr --add gsp      'git stash pop'
abbr --add gsa      'git stash apply'
abbr --add gsc      'git stash clear'
abbr --add ggrep    'git grep'
abbr --add gg       'git grep'
abbr --add grebase  'git rebase'
abbr --add grb      'git rebase'
abbr --add gfetch   'git fetch'
abbr --add gfc      'git fetch'
abbr --add gfom     'git fetch origin master'
abbr --add greset   'git reset'
