# Abbreviations
abbr --add g        'command grep -Pi --color=auto'
abbr --add df       'df -h'
abbr --add du       'du -h --max-depth=1'
abbr --add j        'jobs'
abbr --add g        'grep -Pi --color=auto'
abbr --add ps       'ps -f'
abbr --add pgrep    'pgrep -fau (whoami)'
abbr --add pkill    'pkill -fu (whoami)'
abbr --add kill     'kill -s TERM'
abbr --add fzfdo    'fzf | read -l fzf; and'
abbr --add fzf      'fzf --border --height 40% --min-height 10 --margin 1,5 --reverse --inline-info -1 -0 --bind change:top'
abbr --add pytest   'pytest --verbose --capture no --pdbcls IPython.terminal.debugger:TerminalPdb'
abbr --add less     'less -iR'
abbr --add netstat  'netstat --listening --program --numeric'
abbr --add jq       'jq -C -S'
abbr --add ls       'ls -ahl'
abbr --add ssh      'ssh -A'
abbr --add python   'python3'
abbr --add vim      'nvim'

# Git abbrs
abbr --add gadd     'git add'
abbr --add ga       'git add'
abbr --add grm      'git rm'
abbr --add glog     'git log'
abbr --add glogg    'git log --graph'
abbr --add gstatus  'git status'
abbr --add gs       'git status'
abbr --add gdiff    'git diff --color=always'
abbr --add gpush    'git push'
abbr --add gpom     'git push origin master'
abbr --add gpull    'git pull --rebase'
abbr --add gclone   'git clone'
abbr --add gc       'git commit'
abbr --add gcom     'git commit -m'
abbr --add gca      'git commit -am'
abbr --add gbl      'git blame'
abbr --add gck      'git checkout'
abbr --add gcb      'git checkout -b'
abbr --add gmnf     'git merge --no-ff'
abbr --add gmg      'git merge'
abbr --add gb       'git branch'
abbr --add gbr      'git branch'
abbr --add gbset    'git branch --set-upstream-to origin/master'
abbr --add grrr     'git rerere'
abbr --add gstash   'git stash'
abbr --add gst      'git stash'
abbr --add gsp      'git stash pop'
abbr --add gsa      'git stash apply'
abbr --add gsc      'git stash clear'
abbr --add ggrep    'git grep'
abbr --add gg       'git grep'
abbr --add grebase  'git rebase'
abbr --add grb      'git rebase'
abbr --add gfetch   'git fetch'
abbr --add gfc      'git fetch'
abbr --add gfom     'git fetch origin master'
abbr --add greset   'git reset'

set local_functions (dirname (status --current-filename))/abbr_local.fish
if test -e $local_functions
    source $local_functions
end
